#:schema node_modules/wrangler/config-schema.json
name = "task-manager-app"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "tasks-db"
database_id = "b600a53a-44a0-4815-8029-d135cef974b8"
migrations_dir = "drizzle/migrations"
